live-de-python-main/codigo/Live094/myproject/core/urls.py
from django.urls import path
from myproject.core import views as v


app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
]

live-de-python-main/codigo/Live094/myproject/live/urls.py
from django.urls import path
from myproject.live import views as v


app_name = 'live'


urlpatterns = [
    path('', v.live_list, name='live_list'),
    path('<int:pk>/', v.live_detail, name='live_detail'),
    path('add/', v.LiveCreate.as_view(), name='live_add'),
    path('json/', v.live_json, name='live_json'),
]

live-de-python-main/codigo/Live094/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('live/', include('myproject.live.urls')),
    path('admin/', admin.site.urls),
]

live-de-python-main/codigo/Live094/myproject/core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True

live-de-python-main/codigo/Live094/myproject/live/models.py
from django.db import models
from django.contrib.auth.models import User
from myproject.core.models import TimeStampedModel


class Live(TimeStampedModel):
    number = models.IntegerField('número')
    title = models.TextField('título')
    guest = models.ForeignKey(
        User,
        related_name='guests',
        verbose_name='convidados',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    like = models.PositiveIntegerField('gostou', null=True, blank=True)
    unlike = models.PositiveIntegerField('não gostou', null=True, blank=True)

    class Meta:
        ordering = ('number',)
        verbose_name = "live"
        verbose_name_plural = "lives"

    def __str__(self):
        return self.title

    @property
    def like_frequence(self):
        if self.like:
            return self.unlike / self.like

    def to_dict_json(self):
        data = {
            'pk': self.pk,
            'title': self.title,
            'like': self.like,
            'unlike': self.unlike,
        }
        if self.guest:
            data['guest'] = self.guest.get_full_name()
        return data

live-de-python-main/codigo/Live094/myproject/live/forms.py
from django import forms
from .models import Live


class LiveForm(forms.ModelForm):

    class Meta:
        model = Live
        fields = '__all__'

live-de-python-main/codigo/Live094/myproject/core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

live-de-python-main/codigo/Live094/myproject/live/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .models import Live
from .forms import LiveForm


def live_list(request):
    template_name = 'live/live_list.html'
    object_list = Live.objects.all()
    context = {'object_list': object_list}
    return render(request, template_name, context)


def live_detail(request, pk):
    template_name = 'live/live_detail.html'
    return render(request, template_name)


def live_add(request):
    template_name = 'live/live_form.html'
    return render(request, template_name)


class LiveCreate(CreateView):
    model = Live
    template_name = 'live/live_form.html'
    form_class = LiveForm
    success_url = reverse_lazy('live:live_list')


def live_json(request):
    lives = Live.objects.all()
    data = [live.to_dict_json() for live in lives]
    return JsonResponse({'data': data})

live-de-python-main/codigo/Live094/myproject/core/templates/base.html
<!-- https://getbootstrap.com/docs/4.0/getting-started/introduction/#starter-template -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
  <!-- <link rel="shortcut icon" href="http://html5-training-in-hyderabad.blogspot.com.br/favicon.ico"> -->
  <title>Estoque</title>
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <style>
    body {
      margin-top: 60px;
    }
  </style>

  {% block css %}{% endblock css %}

  </body>
</head>
<body>

  {% include "includes/nav.html" %}

  <div class="container">
    {% block content %}{% endblock content %}
  </div>

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

  {% block js %}{% endblock js %}

</body>
</html>

live-de-python-main/codigo/Live094/myproject/core/templates/includes/nav.html
<!-- https://getbootstrap.com/docs/4.0/examples/starter-template/ -->
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'core:index' %}">Live 94</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'live:live_list' %}">Lives</a>
            </li>
            <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li> -->
        </ul>
    </div>
</nav>

live-de-python-main/codigo/Live094/myproject/core/templates/index.html
{% extends "base.html" %}

{% block content %}

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to Live of Python 94!</h1>
    <p>This is a introduction to Django.</p>
    <p>
      <a href="">
        <button class="btn btn-primary btn-lg" type="button">
          Cadastrar <span class="fa fa-plus"></span>
        </button>
      </a>
    </p>
  </div>
</div>

<div class="text-center mt-5 pt-5">
    <h1>Bootstrap starter template</h1>
    <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
</div>

{% endblock content %}

live-de-python-main/codigo/Live094/myproject/live/templates/live/live_detail.html
{% extends "base.html" %}

{% block content %}

<h1>Live 1</h1>

{% endblock content %}

live-de-python-main/codigo/Live094/myproject/live/templates/live/live_form.html
{% extends "base.html" %}

{% block content %}

<h1>Nova Live</h1>

<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-primary" type="submit">Salvar</button>
</form>

{% endblock content %}

live-de-python-main/codigo/Live094/myproject/live/templates/live/live_list.html
{% extends "base.html" %}

{% block content %}

<div class="row">
  <div class="col-sm-6">
    <form action="." method="GET" class="form-inline">
      <input type="text" id="search" name="search" class="form-control" placeholder="Busca">
      <input type="submit" class="btn btn-primary" style="margin-left: 10px;" value="OK">
    </form>
  </div>
</div>

<div class="page-header">
  <h2>Lives
    <span class="pull-right">
      <a href="{% url 'live:live_add' %}">
        <button type="button" class="btn btn-primary">
          <span class="fa fa-plus"></span> Adicionar
        </button>
      </a>
    </span>
  </h2>

  {% if object_list %}
    
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="text-center">Live</th>
          <th>Título</th>
          <th>Convidado</th>
          <th><i class="fa fa-thumbs-o-up"></i></th>
          <th><i class="fa fa-thumbs-o-down"></i></th>
          <th>Frequência</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
          <tr>
            <td class="text-center">{{ object.number }}</td>
            <td>{{ object.title }}</td>
            <td>{{ object.guest.get_full_name|default:'---' }}</td>
            <td>{{ object.like }}</td>
            <td>{{ object.unlike }}</td>
            <td>{{ object.like_frequence|floatformat:3 }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
  {% endif %}

</div>

{% endblock content %}